In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd drive/MyDrive/MiniProject/Project

/content/drive/MyDrive/MiniProject/Project


In [3]:
import numpy as np
import random
import os

In [54]:
for i in range(1, 5):
    os.mkdir("Data/Type"+str(i)+"Small")
    os.mkdir("Data/Type"+str(i)+"Big")

In [55]:
def createRandomSortedList(low = 1, high = 100, size = 1):
    arr = []
    tmp = np.random.randint(low, high)
      
    for x in range(size):         
        while tmp in arr:
            tmp = random.randint(low, high)            
        arr.append(tmp)
          
    arr.sort()
      
    return np.array(arr)

In [48]:
# Thu 4-7 cánh đồng 1 ngày, range = 4, không có min = 0
def create1(N, m, M, Type):
    f = open("Data/"+Type+"/"+str(N)+"-"+str(m)+"-"+str(M)+".txt", "w")
    print(N, " ", m, " ", M)
    f.write(str(N)+" "+str(m)+" "+str(M)+"\n")

    rangeDay = np.random.randint(N/7, N/4) + 1  # so ngay gioi han uoc luong
    print(rangeDay)
    # san luong thu moi ngay
    amount = np.random.randint(m, M+1, size=rangeDay)
    amount = np.sort(amount)
    print(amount)
    # so canh dong cua ngay do duoc chon random
    count = np.array([int(N/rangeDay)] * rangeDay)
    while (np.sum(count) < N):
        for i in range(rangeDay):
            # uu tien chia cac canh dong lon truoc
            day = rangeDay - 1 - i
            count[day] += 1
            if (np.sum(count) == N):
                break
    print(count)
    d = []
    s = []
    e = []
    # chia sản lượng cho các cánh đồng cùng ngày
    for day in range(rangeDay):
        mark = createRandomSortedList(1, amount[day], size=count[day]+1)
        mark[0] = 0
        mark[count[day]] = amount[day]
        for j in range(count[day]):
            d.append(mark[j+1]-mark[j])

            start = max(day-np.random.randint(4), 0)
            end = min(day+np.random.randint(4), rangeDay-1)
            # if (start<0):
            #     end-=start
            #     start=0
            # if (end>=rangeDay):
            #     start-=end-rangeDay-1
            #     end =rangeDay-1
            s.append(start)
            e.append(end)

    e = np.array(e) - min(s)
    s = np.array(s) - min(s)
    print(d)
    print(s)
    print(e)

    randomOrder = np.arange(N)
    np.random.shuffle(randomOrder)
    for i in randomOrder:
        f.write(str(d[i])+" "+str(int(s[i]))+" "+str(int(e[i]))+"\n")

    f.close()


In [49]:
# Thu 4-7 cánh đồng 1 ngày, range = 7, không có min = 0
def create2(N, m, M, Type):
    f = open("Data/"+Type+"/"+str(N)+"-"+str(m)+"-"+str(M)+".txt", "w")
    print(N, " ", m, " ", M)
    f.write(str(N)+" "+str(m)+" "+str(M)+"\n")

    rangeDay = np.random.randint(N/7, N/4)+1  # so ngay gioi han uoc luong
    print(rangeDay)
    # san luong thu moi ngay
    amount = np.random.randint(m, M+1, size=rangeDay)
    amount = np.sort(amount)
    print(amount)
    # so canh dong cua ngay do duoc chon random
    count = np.array([int(N/rangeDay)]*rangeDay)
    while (np.sum(count) < N):
        for i in range(rangeDay):
            # uu tien chia cac canh dong lon truoc
            day = rangeDay-1-i
            count[day] += 1
            if (np.sum(count) == N):
                break
    print(count)
    d = []
    s = []
    e = []
    # chia sản lượng cho các cánh đồng cùng ngày
    for day in range(rangeDay):
        mark = createRandomSortedList(1, amount[day], size=count[day]+1)
        mark[0] = 0
        mark[count[day]] = amount[day]
        for j in range(count[day]):
            d.append(mark[j+1]-mark[j])

            start = max(day-np.random.randint(7), 0)
            end = min(day+np.random.randint(7), rangeDay-1)
            # if (start<0):
            #     end-=start
            #     start=0
            # if (end>=rangeDay):
            #     start-=end-rangeDay-1
            #     end =rangeDay-1
            s.append(start)
            e.append(end)

    e = np.array(e) - min(s)
    s = np.array(s) - min(s)
    print(d)
    print(s)
    print(e)

    randomOrder = np.arange(N)
    np.random.shuffle(randomOrder)
    for i in randomOrder:
        f.write(str(d[i])+" "+str(int(s[i]))+" "+str(int(e[i]))+"\n")

    f.close()


In [50]:
# Thu 4-7 cánh đồng 1 ngày, range = 4, có min = 0
def create3(N, m, M, Type):
    f = open("Data/"+Type+"/"+str(N)+"-"+str(m)+"-"+str(M)+".txt", "w")
    print(N, " ", m, " ", M)
    f.write(str(N)+" "+str(m)+" "+str(M)+"\n")

    rangeDay = np.random.randint(N/7, N/4)+1  # so ngay gioi han uoc luong
    print(rangeDay)
    # san luong thu moi ngay
    amount = np.random.randint(m, M+1, size=rangeDay)
    amount = np.sort(amount)
    print(amount)
    # so canh dong cua ngay do
    count = np.array([int(N/rangeDay)]*rangeDay)
    while (np.sum(count) < N):
        for i in range(rangeDay):
            # uu tien chia cac canh dong lon truoc
            day = rangeDay-1-i
            count[day] += 1
            if (np.sum(count) == N):
                break

    print(count)
    d = []
    s = []
    e = []
    # chia sản lượng cho các cánh đồng cùng ngày
    for day in range(rangeDay):
        mark = createRandomSortedList(1, amount[day], size=count[day]+1)
        mark[0] = 0
        mark[count[day]] = amount[day]
        for j in range(count[day]):
            d.append(mark[j+1]-mark[j])
            s.append(day-np.random.randint(4))
            e.append(day+np.random.randint(4))

    e = np.array(e) - min(s)
    s = np.array(s) - min(s)
    print(d)
    print(s)
    print(e)

    randomOrder = np.arange(N)
    np.random.shuffle(randomOrder)
    for i in randomOrder:
        f.write(str(d[i])+" "+str(int(s[i]))+" "+str(int(e[i]))+"\n")

    f.close()


In [51]:
# Thu 10 cánh đồng 1 ngày, range = 5, không có min = 0
def create4(N, m, M, Type):
    f = open("Data/"+Type+"/"+str(N)+"-"+str(m)+"-"+str(M)+".txt", "w")
    print(N, " ", m, " ", M)
    f.write(str(N)+" "+str(m)+" "+str(M)+"\n")

    rangeDay = int(N/10) + 1  # so ngay gioi han uoc luong
    print(rangeDay)
    # san luong thu moi ngay
    amount = np.random.randint(m, M+1, size=rangeDay)
    amount = np.sort(amount)
    print(amount)
    # so canh dong cua ngay do duoc chon random
    count = np.array([int(N/rangeDay)]*rangeDay)
    while (np.sum(count) < N):
        for i in range(rangeDay):
            # uu tien chia cac canh dong lon truoc
            day = rangeDay-1-i
            count[day] += 1
            if (np.sum(count) == N):
                break
    print(count)
    d = []
    s = []
    e = []
    # chia sản lượng cho các cánh đồng cùng ngày
    for day in range(rangeDay):
        mark = createRandomSortedList(1, amount[day], size=count[day]+1)
        mark[0] = 0
        mark[count[day]] = amount[day]
        for j in range(count[day]):
            d.append(mark[j+1]-mark[j])

            start = max(day-np.random.randint(5), 0)
            end = min(day+np.random.randint(5), rangeDay-1)
            # if (start<0):
            #     end-=start
            #     start=0
            # if (end>=rangeDay):
            #     start-=end-rangeDay-1
            #     end =rangeDay-1
            s.append(start)
            e.append(end)

    e = np.array(e) - min(s)
    s = np.array(s) - min(s)
    print(d)
    print(s)
    print(e)

    randomOrder = np.arange(N)
    np.random.shuffle(randomOrder)
    for i in randomOrder:
        f.write(str(d[i])+" "+str(int(s[i]))+" "+str(int(e[i]))+"\n")

    f.close()


In [56]:
low = [10, 20, 35, 50]
high = [15, 30, 50, 75]
for N in [10, 20, 40, 60]:
    for i in range(4):
        m = low[i]
        M = high[i]
        create1(N, m, M, "Type1Small")
        create2(N, m, M, "Type2Small")
        create3(N, m, M, "Type3Small")
        create4(N, m, M, "Type4Small")


10   10   15
2
[12 15]
[5 5]
[6, 1, 2, 1, 2, 4, 1, 1, 5, 4]
[0 0 0 0 0 0 0 0 1 1]
[1 1 1 1 1 1 1 1 1 1]
10   10   15
2
[12 12]
[5 5]
[3, 5, 2, 1, 1, 5, 1, 2, 1, 3]
[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 0 1 1 1 1 1]
10   10   15
2
[12 15]
[5 5]
[2, 2, 6, 1, 1, 2, 3, 3, 2, 5]
[0 1 1 2 0 1 4 3 2 2]
[3 5 5 6 6 7 5 4 6 5]
10   10   15
2
[11 13]
[5 5]
[5, 1, 1, 1, 3, 5, 2, 2, 1, 3]
[0 0 0 0 0 0 0 0 0 0]
[1 0 1 1 1 1 1 1 1 1]
10   20   30
2
[27 28]
[5 5]
[9, 3, 1, 8, 6, 5, 3, 2, 14, 4]
[0 0 0 0 0 0 0 0 1 1]
[0 1 1 1 1 1 1 1 1 1]
10   20   30
2
[21 22]
[5 5]
[10, 1, 1, 5, 4, 6, 3, 8, 1, 4]
[0 0 0 0 0 0 0 0 1 1]
[1 1 1 1 1 1 1 1 1 1]
10   20   30
2
[25 27]
[5 5]
[7, 3, 1, 1, 13, 4, 3, 5, 13, 2]
[2 0 2 3 0 4 1 4 2 1]
[6 3 3 4 5 4 5 7 5 6]
10   20   30
2
[22 28]
[5 5]
[3, 3, 4, 5, 7, 7, 1, 3, 9, 8]
[0 0 0 0 0 0 0 0 0 0]
[1 1 0 1 1 1 1 1 1 1]
10   35   50
2
[40 47]
[5 5]
[7, 5, 2, 2, 24, 13, 6, 7, 5, 16]
[0 0 0 0 0 1 1 0 0 0]
[1 0 1 1 0 1 1 1 1 1]
10   35   50
2
[46 49]
[5 5]
[8, 3, 8, 11, 16, 25, 2, 2, 

In [57]:
low = [20, 30, 40, 50]
high = [30, 45, 60, 80]
for N in [200, 400, 600, 800]:
    for i in range(4):
        m = low[i]
        M = high[i]
        create1(N, m, M, "Type1Big")
        create2(N, m, M, "Type2Big")
        create3(N, m, M, "Type3Big")
        create4(N, m, M, "Type4Big")


200   20   30
44
[20 20 20 20 20 21 21 21 21 21 22 22 22 23 23 24 24 24 25 25 25 25 26 26
 26 26 26 26 27 27 27 27 27 27 28 28 29 29 29 30 30 30 30 30]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5]
[8, 6, 1, 5, 7, 5, 4, 4, 7, 2, 6, 5, 3, 1, 3, 13, 2, 2, 11, 5, 7, 5, 2, 7, 5, 2, 4, 10, 8, 3, 4, 6, 5, 7, 1, 8, 5, 3, 10, 3, 9, 3, 5, 5, 7, 2, 5, 8, 6, 7, 5, 4, 8, 5, 1, 9, 3, 2, 6, 12, 6, 12, 1, 5, 9, 3, 7, 5, 10, 6, 1, 7, 5, 2, 8, 10, 4, 2, 4, 15, 5, 8, 3, 4, 5, 9, 3, 4, 1, 8, 9, 2, 1, 1, 13, 4, 2, 2, 1, 17, 9, 5, 1, 4, 7, 13, 1, 2, 6, 4, 4, 1, 2, 2, 17, 12, 4, 3, 1, 6, 6, 2, 8, 3, 8, 12, 5, 1, 2, 7, 8, 4, 2, 10, 3, 4, 9, 2, 7, 5, 15, 4, 1, 2, 5, 3, 6, 1, 1, 16, 11, 8, 1, 5, 3, 7, 7, 4, 3, 7, 4, 7, 9, 1, 8, 13, 1, 2, 1, 12, 2, 11, 4, 6, 6, 10, 1, 3, 4, 12, 9, 5, 5, 10, 1, 6, 5, 2, 6, 11, 11, 3, 4, 6, 6, 6, 3, 3, 3, 15]
[ 0  0  0  0  0  0  0  0  0  2  0  2  2  1  0  1  1  3  3  4  4  4  4  2
  6  3  5  5  5  5  4  5  5  6  5  5  7  8  7  8  8  9 